# @package _global_
defaults:
  - override /model: rnndet

model:
  backbone:
    name: SNNSwin
    input_channels: 20
    enable_masking: false
    embed_dim: 40
    depths: [2, 2, 2, 2]
    num_heads: [2, 4, 8, 8]
    window_sizes: [8, 8, 4, null]
    mlp_ratio: 4.0
    attn_scale: 0.125
    output_scale: 0.25
    snn:
      beta_init: 0.5
      learn_beta: true
      threshold: 1.0
      reset_mechanism: subtract
  fpn:
    name: PAFPN
    compile:
      enable: false
      args:
        mode: reduce-overhead
    depth: 0.67
    in_stages: [2, 3, 4]
    depthwise: false
    act: "silu"
  head:
    name: YoloX
    compile:
      enable: false
      args:
        mode: reduce-overhead
    depthwise: false
    act: "silu"
  postprocess:
    confidence_threshold: 0.1
    nms_threshold: 0.45
